/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import BaseDatos.DataBase;
import Clases.GestorUsuarios;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.security.util.Length;

/**
 *
 * @author santi
 */
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas
     */
    private Menu m;
    private DefaultTableModel modeloTabla;

    public Estadisticas(Menu m) {
        initComponents();
        this.m = m;
        modeloTabla = (DefaultTableModel) tablaEstadisticas.getModel();

        this.setLocationRelativeTo(null);
        this.setTitle("Ruleta SF - Iniciar Sesión");
        this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/login.png")).getImage());

        cargaTabla(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstadisticas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btCerrar = new javax.swing.JButton();
        dcFechaFiltro = new com.toedter.calendar.JDateChooser();
        btFiltrar = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        labelMedia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jScrollPane1.setBackground(new java.awt.Color(102, 255, 102));

        tablaEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ganancias", "Fichas Iniciales", "Fichas Finales", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEstadisticas);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("ESTADÍSTICAS");

        btCerrar.setText("Cerrar");
        btCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCerrarMouseExited(evt);
            }
        });
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        dcFechaFiltro.setDateFormatString("dd-MM-yyyy");

        btFiltrar.setText("Filtrar");
        btFiltrar.setToolTipText("Filtra por fecha ");
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });

        labelTotal.setText("Total de Ganancias: ");

        labelMedia.setText("Media de Ganancias: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dcFechaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(btFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMedia)
                            .addComponent(labelTotal))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcFechaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTotal)
                .addGap(18, 18, 18)
                .addComponent(labelMedia)
                .addGap(49, 49, 49)
                .addComponent(btCerrar)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarMouseEntered
        // TODO add your handling code here:
        btCerrar.setBackground(Color.RED);
    }//GEN-LAST:event_btCerrarMouseEntered

    private void btCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarMouseExited
        // TODO add your handling code here:
        btCerrar.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_btCerrarMouseExited

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCerrarActionPerformed

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
        // TODO add your handling code here:
        cargaTabla(dcFechaFiltro.getDate());
    }//GEN-LAST:event_btFiltrarActionPerformed

    private void cargaTabla(Date fechaFiltro) {
        //Carga los datos en la tabla
        limpiaTabla();

        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            if (fechaFiltro == null) {
                //Sin filtros
                ps = DataBase.getConexion().prepareStatement("Select GANANCIAS, FICHASINICIALES, FICHASFINALES, FECHAREALIZACION "
                        + "from ESTADISTICASUSUARIO "
                        + "where USUARIO_IDUSUARIO = ?");
                ps.setInt(1, GestorUsuarios.getUsuarioActivo().getId());
                rs = ps.executeQuery();

                //Media
                int media = 0;
                int numFilas = 0;

                if (rs.isBeforeFirst()) {
                    while (rs.next()) {
                        modeloTabla.addRow(new String[]{rs.getInt(1) + "", rs.getInt(2) + "", rs.getInt(3) + "",
                            rs.getDate(4).toString()});

                        media += rs.getInt(1);
                        numFilas++;
                    }
                    labelTotal.setText("Total de Ganancias: " + media);
                    labelMedia.setText("Media de Ganancias: " + media / numFilas);
                } else {
                    JOptionPane.showMessageDialog(this, "No se ha encontrado ningun dato", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                    labelTotal.setText("Total de Ganancias: 0");
                    labelMedia.setText("Media de Ganancias: 0");
                }

            } else {
                //Con filtros
                ps = DataBase.getConexion().prepareStatement("Select GANANCIAS, FICHASINICIALES, FICHASFINALES, FECHAREALIZACION "
                        + "from ESTADISTICASUSUARIO "
                        + "where USUARIO_IDUSUARIO = ? AND TO_DATE(FECHAREALIZACION, 'dd/MM/yy') = TO_DATE(?, 'dd/MM/yy')");
                ps.setInt(1, GestorUsuarios.getUsuarioActivo().getId());
                ps.setDate(2, new java.sql.Date(fechaFiltro.getTime()));
                rs = ps.executeQuery();

                //Media
                int media = 0;
                int numFilas = 0;

                if (rs.isBeforeFirst()) {
                    while (rs.next()) {
                        modeloTabla.addRow(new String[]{rs.getInt(1) + "", rs.getInt(2) + "", rs.getInt(3) + "",
                            rs.getDate(4).toString()});

                        media += rs.getInt(1);
                        numFilas++;
                    }
                    labelTotal.setText("Total de Ganancias: " + media);
                    labelMedia.setText("Media de Ganancias: " + media / numFilas);
                } else {
                    JOptionPane.showMessageDialog(this, "No se ha encontrado ningun dato", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                    labelTotal.setText("Total de Ganancias: 0");
                    labelMedia.setText("Media de Ganancias: 0");
                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Problemas con SQL: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiaTabla() {
//        for (int i = 0; i < tablaEstadisticas.getRowCount(); i++) {
//            modeloTabla.removeRow(0);
//        }
        while (tablaEstadisticas.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btFiltrar;
    private com.toedter.calendar.JDateChooser dcFechaFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMedia;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tablaEstadisticas;
    // End of variables declaration//GEN-END:variables
}
