/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.GestorUsuarios;
import Clases.Mesa;
import Clases.Resultado;
import java.awt.Color;
import java.awt.Component;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class Jugar extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Jugar
     */
    private Menu m;
    private int fichaSeleccionada;

//    private Socket cliente;
//    private DataInputStream entrada;
//    private DataOutputStream salida;

    //Botones numeros
    public static ArrayList<JButton> botones;

    //Fichas
    private int fichas;
    private int fichasPreApuesta;
    //Apuestas
    private int apuestaRojo;
    private int apuestaNegro;
    private int apuestaPar;
    private int apuestaImpar;
    private int[] apuestaDocenas;
    private int[] apuestaBajo1Alto2;
    private int[] apuestaFilas;
    private int[] apuestaNumeros;

    public Jugar(Menu m) {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Ruleta SF - Jugar");
        this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/Logo.png")).getImage());

        //Si el usuario es un usuario invitado se le proporcionan 100 fichas
        if (GestorUsuarios.getUsuarioActivo() == null) {
            fichas = 100;
        } else {
            fichas = GestorUsuarios.getUsuarioActivo().getFichasFinales();
        }
        //Variable auxiliar para saber si hay apuestas en la mesa
        fichasPreApuesta = fichas;
        botones = new ArrayList<JButton>();
        botones.add(btNumero0);
        botones.add(btNumero1);
        botones.add(btNumero2);
        botones.add(btNumero3);
        botones.add(btNumero4);
        botones.add(btNumero5);
        botones.add(btNumero6);
        botones.add(btNumero7);
        botones.add(btNumero8);
        botones.add(btNumero9);
        botones.add(btNumero10);
        botones.add(btNumero11);
        botones.add(btNumero12);
        botones.add(btNumero13);
        botones.add(btNumero14);
        botones.add(btNumero15);
        botones.add(btNumero16);
        botones.add(btNumero17);
        botones.add(btNumero18);
        botones.add(btNumero19);
        botones.add(btNumero20);
        botones.add(btNumero21);
        botones.add(btNumero22);
        botones.add(btNumero23);
        botones.add(btNumero24);
        botones.add(btNumero25);
        botones.add(btNumero26);
        botones.add(btNumero27);
        botones.add(btNumero28);
        botones.add(btNumero29);
        botones.add(btNumero30);
        botones.add(btNumero31);
        botones.add(btNumero32);
        botones.add(btNumero33);
        botones.add(btNumero34);
        botones.add(btNumero35);
        botones.add(btNumero36);

        labelFichas.setText("Fichas: " + fichas);

        //Inicializar variables
        this.m = m;
        fichaSeleccionada = 1;
//        this.cliente = cliente;
        this.apuestaDocenas = new int[3];
        this.apuestaBajo1Alto2 = new int[2];
        this.apuestaFilas = new int[3];
        this.apuestaNumeros = new int[37];

//        try {
//            //Inicializa los flujos
//            entrada = new DataInputStream(cliente.getInputStream()); //Canal de entrada
//            salida = new DataOutputStream(cliente.getOutputStream()); //canal de salida
//        } catch (IOException ex) {
//            JOptionPane.showMessageDialog(this, "Ha habido un problema conectandose con el servidor");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoFichas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();
        panelFichas = new javax.swing.JPanel();
        tbFicha2 = new javax.swing.JToggleButton();
        tbFicha1 = new javax.swing.JToggleButton();
        tbFicha5 = new javax.swing.JToggleButton();
        tbFicha20 = new javax.swing.JToggleButton();
        tbFicha100 = new javax.swing.JToggleButton();
        tbFichaBorrar = new javax.swing.JToggleButton();
        labelFichas = new javax.swing.JLabel();
        panelMesa = new javax.swing.JPanel();
        panelMesaHijo = new javax.swing.JPanel();
        panelNumeros = new javax.swing.JPanel();
        btNumero3 = new javax.swing.JButton();
        btNumero6 = new javax.swing.JButton();
        btNumero9 = new javax.swing.JButton();
        btNumero12 = new javax.swing.JButton();
        btNumero15 = new javax.swing.JButton();
        btNumero18 = new javax.swing.JButton();
        btNumero21 = new javax.swing.JButton();
        btNumero24 = new javax.swing.JButton();
        btNumero27 = new javax.swing.JButton();
        btNumero30 = new javax.swing.JButton();
        btNumero33 = new javax.swing.JButton();
        btNumero36 = new javax.swing.JButton();
        btNumero2 = new javax.swing.JButton();
        btNumero5 = new javax.swing.JButton();
        btNumero8 = new javax.swing.JButton();
        btNumero11 = new javax.swing.JButton();
        btNumero14 = new javax.swing.JButton();
        btNumero17 = new javax.swing.JButton();
        btNumero20 = new javax.swing.JButton();
        btNumero23 = new javax.swing.JButton();
        btNumero26 = new javax.swing.JButton();
        btNumero29 = new javax.swing.JButton();
        btNumero32 = new javax.swing.JButton();
        btNumero35 = new javax.swing.JButton();
        btNumero1 = new javax.swing.JButton();
        btNumero4 = new javax.swing.JButton();
        btNumero7 = new javax.swing.JButton();
        btNumero10 = new javax.swing.JButton();
        btNumero13 = new javax.swing.JButton();
        btNumero16 = new javax.swing.JButton();
        btNumero19 = new javax.swing.JButton();
        btNumero22 = new javax.swing.JButton();
        btNumero25 = new javax.swing.JButton();
        btNumero28 = new javax.swing.JButton();
        btNumero31 = new javax.swing.JButton();
        btNumero34 = new javax.swing.JButton();
        panelColumnas = new javax.swing.JPanel();
        btColumna3 = new javax.swing.JButton();
        btColumna2 = new javax.swing.JButton();
        btColumna1 = new javax.swing.JButton();
        btNumero0 = new javax.swing.JButton();
        panelDocenas = new javax.swing.JPanel();
        btDocena1 = new javax.swing.JButton();
        btDocena2 = new javax.swing.JButton();
        btDocena3 = new javax.swing.JButton();
        panelColores = new javax.swing.JPanel();
        btBajos = new javax.swing.JButton();
        btPar = new javax.swing.JButton();
        btRojo = new javax.swing.JButton();
        btNegro = new javax.swing.JButton();
        btImpar = new javax.swing.JButton();
        btAltos = new javax.swing.JButton();
        btCerrar = new javax.swing.JButton();
        labelTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        panelLog.setBackground(new java.awt.Color(102, 255, 102));
        panelLog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        taLog.setBackground(new java.awt.Color(102, 255, 102));
        taLog.setColumns(20);
        taLog.setRows(5);
        taLog.setEnabled(false);
        taLog.setFocusable(false);
        jScrollPane1.setViewportView(taLog);

        javax.swing.GroupLayout panelLogLayout = new javax.swing.GroupLayout(panelLog);
        panelLog.setLayout(panelLogLayout);
        panelLogLayout.setHorizontalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        panelLogLayout.setVerticalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        panelFichas.setBackground(new java.awt.Color(102, 255, 102));
        panelFichas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tbFicha2.setBackground(new java.awt.Color(153, 255, 153));
        grupoFichas.add(tbFicha2);
        tbFicha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ficha2.png"))); // NOI18N
        tbFicha2.setToolTipText("Seleccionar ficha: 2");
        tbFicha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFicha2ActionPerformed(evt);
            }
        });

        tbFicha1.setBackground(new java.awt.Color(153, 255, 153));
        grupoFichas.add(tbFicha1);
        tbFicha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ficha1.png"))); // NOI18N
        tbFicha1.setSelected(true);
        tbFicha1.setToolTipText("Seleccionar ficha: 1");
        tbFicha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFicha1ActionPerformed(evt);
            }
        });

        tbFicha5.setBackground(new java.awt.Color(153, 255, 153));
        grupoFichas.add(tbFicha5);
        tbFicha5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ficha5.png"))); // NOI18N
        tbFicha5.setToolTipText("Seleccionar ficha: 5");
        tbFicha5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFicha5ActionPerformed(evt);
            }
        });

        tbFicha20.setBackground(new java.awt.Color(153, 255, 153));
        grupoFichas.add(tbFicha20);
        tbFicha20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ficha20.png"))); // NOI18N
        tbFicha20.setToolTipText("Seleccionar ficha: 20");
        tbFicha20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFicha20ActionPerformed(evt);
            }
        });

        tbFicha100.setBackground(new java.awt.Color(153, 255, 153));
        grupoFichas.add(tbFicha100);
        tbFicha100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ficha100.png"))); // NOI18N
        tbFicha100.setToolTipText("Seleccionar ficha: 100");
        tbFicha100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFicha100ActionPerformed(evt);
            }
        });

        tbFichaBorrar.setBackground(new java.awt.Color(153, 255, 153));
        grupoFichas.add(tbFichaBorrar);
        tbFichaBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/borrar.png"))); // NOI18N
        tbFichaBorrar.setToolTipText("Borrar Apuesta");
        tbFichaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFichaBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFichasLayout = new javax.swing.GroupLayout(panelFichas);
        panelFichas.setLayout(panelFichasLayout);
        panelFichasLayout.setHorizontalGroup(
            panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFichasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbFicha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100)
                .addComponent(tbFicha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100)
                .addComponent(tbFicha5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100)
                .addComponent(tbFicha20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(101, 101, 101)
                .addComponent(tbFicha100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(111, 111, 111)
                .addComponent(tbFichaBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFichasLayout.setVerticalGroup(
            panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFichasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbFicha100, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(tbFicha20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tbFicha5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tbFicha1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tbFicha2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tbFichaBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        labelFichas.setText("Fichas: ");

        panelMesa.setBackground(new java.awt.Color(102, 255, 102));
        panelMesa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        panelMesaHijo.setBackground(new java.awt.Color(102, 255, 102));

        panelNumeros.setBackground(new java.awt.Color(102, 255, 102));
        panelNumeros.setLayout(new java.awt.GridLayout(3, 13));

        btNumero3.setBackground(new java.awt.Color(255, 0, 0));
        btNumero3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero3.setForeground(new java.awt.Color(255, 255, 255));
        btNumero3.setText("3");
        btNumero3.setToolTipText("Numero (35:1)");
        btNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero3ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero3);

        btNumero6.setBackground(new java.awt.Color(0, 0, 0));
        btNumero6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero6.setForeground(new java.awt.Color(255, 255, 255));
        btNumero6.setText("6");
        btNumero6.setToolTipText("Numero (35:1)");
        btNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero6ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero6);

        btNumero9.setBackground(new java.awt.Color(255, 0, 0));
        btNumero9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero9.setForeground(new java.awt.Color(255, 255, 255));
        btNumero9.setText("9");
        btNumero9.setToolTipText("Numero (35:1)");
        btNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero9ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero9);

        btNumero12.setBackground(new java.awt.Color(255, 0, 0));
        btNumero12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero12.setForeground(new java.awt.Color(255, 255, 255));
        btNumero12.setText("12");
        btNumero12.setToolTipText("Numero (35:1)");
        btNumero12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero12ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero12);

        btNumero15.setBackground(new java.awt.Color(0, 0, 0));
        btNumero15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero15.setForeground(new java.awt.Color(255, 255, 255));
        btNumero15.setText("15");
        btNumero15.setToolTipText("Numero (35:1)");
        btNumero15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero15ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero15);

        btNumero18.setBackground(new java.awt.Color(255, 0, 0));
        btNumero18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero18.setForeground(new java.awt.Color(255, 255, 255));
        btNumero18.setText("18");
        btNumero18.setToolTipText("Numero (35:1)");
        btNumero18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero18ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero18);

        btNumero21.setBackground(new java.awt.Color(255, 0, 0));
        btNumero21.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero21.setForeground(new java.awt.Color(255, 255, 255));
        btNumero21.setText("21");
        btNumero21.setToolTipText("Numero (35:1)");
        btNumero21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero21ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero21);

        btNumero24.setBackground(new java.awt.Color(0, 0, 0));
        btNumero24.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero24.setForeground(new java.awt.Color(255, 255, 255));
        btNumero24.setText("24");
        btNumero24.setToolTipText("Numero (35:1)");
        btNumero24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero24ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero24);

        btNumero27.setBackground(new java.awt.Color(255, 0, 0));
        btNumero27.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero27.setForeground(new java.awt.Color(255, 255, 255));
        btNumero27.setText("27");
        btNumero27.setToolTipText("Numero (35:1)");
        btNumero27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero27ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero27);

        btNumero30.setBackground(new java.awt.Color(255, 0, 0));
        btNumero30.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero30.setForeground(new java.awt.Color(255, 255, 255));
        btNumero30.setText("30");
        btNumero30.setToolTipText("Numero (35:1)");
        btNumero30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero30ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero30);

        btNumero33.setBackground(new java.awt.Color(0, 0, 0));
        btNumero33.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero33.setForeground(new java.awt.Color(255, 255, 255));
        btNumero33.setText("33");
        btNumero33.setToolTipText("Numero (35:1)");
        btNumero33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero33ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero33);

        btNumero36.setBackground(new java.awt.Color(255, 0, 0));
        btNumero36.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero36.setForeground(new java.awt.Color(255, 255, 255));
        btNumero36.setText("36");
        btNumero36.setToolTipText("Numero (35:1)");
        btNumero36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero36ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero36);

        btNumero2.setBackground(new java.awt.Color(0, 0, 0));
        btNumero2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero2.setForeground(new java.awt.Color(255, 255, 255));
        btNumero2.setText("2");
        btNumero2.setToolTipText("Numero (35:1)");
        btNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero2ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero2);

        btNumero5.setBackground(new java.awt.Color(255, 0, 0));
        btNumero5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero5.setForeground(new java.awt.Color(255, 255, 255));
        btNumero5.setText("5");
        btNumero5.setToolTipText("Numero (35:1)");
        btNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero5ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero5);

        btNumero8.setBackground(new java.awt.Color(0, 0, 0));
        btNumero8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero8.setForeground(new java.awt.Color(255, 255, 255));
        btNumero8.setText("8");
        btNumero8.setToolTipText("Numero (35:1)");
        btNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero8ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero8);

        btNumero11.setBackground(new java.awt.Color(0, 0, 0));
        btNumero11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero11.setForeground(new java.awt.Color(255, 255, 255));
        btNumero11.setText("11");
        btNumero11.setToolTipText("Numero (35:1)");
        btNumero11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero11ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero11);

        btNumero14.setBackground(new java.awt.Color(255, 0, 0));
        btNumero14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero14.setForeground(new java.awt.Color(255, 255, 255));
        btNumero14.setText("14");
        btNumero14.setToolTipText("Numero (35:1)");
        btNumero14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero14ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero14);

        btNumero17.setBackground(new java.awt.Color(0, 0, 0));
        btNumero17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero17.setForeground(new java.awt.Color(255, 255, 255));
        btNumero17.setText("17");
        btNumero17.setToolTipText("Numero (35:1)");
        btNumero17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero17ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero17);

        btNumero20.setBackground(new java.awt.Color(0, 0, 0));
        btNumero20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero20.setForeground(new java.awt.Color(255, 255, 255));
        btNumero20.setText("20");
        btNumero20.setToolTipText("Numero (35:1)");
        btNumero20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero20ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero20);

        btNumero23.setBackground(new java.awt.Color(255, 0, 0));
        btNumero23.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero23.setForeground(new java.awt.Color(255, 255, 255));
        btNumero23.setText("23");
        btNumero23.setToolTipText("Numero (35:1)");
        btNumero23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero23ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero23);

        btNumero26.setBackground(new java.awt.Color(0, 0, 0));
        btNumero26.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero26.setForeground(new java.awt.Color(255, 255, 255));
        btNumero26.setText("26");
        btNumero26.setToolTipText("Numero (35:1)");
        btNumero26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero26ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero26);

        btNumero29.setBackground(new java.awt.Color(0, 0, 0));
        btNumero29.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero29.setForeground(new java.awt.Color(255, 255, 255));
        btNumero29.setText("29");
        btNumero29.setToolTipText("Numero (35:1)");
        btNumero29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero29ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero29);

        btNumero32.setBackground(new java.awt.Color(255, 0, 0));
        btNumero32.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero32.setForeground(new java.awt.Color(255, 255, 255));
        btNumero32.setText("32");
        btNumero32.setToolTipText("Numero (35:1)");
        btNumero32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero32ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero32);

        btNumero35.setBackground(new java.awt.Color(0, 0, 0));
        btNumero35.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero35.setForeground(new java.awt.Color(255, 255, 255));
        btNumero35.setText("35");
        btNumero35.setToolTipText("Numero (35:1)");
        btNumero35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero35ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero35);

        btNumero1.setBackground(new java.awt.Color(255, 0, 0));
        btNumero1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero1.setForeground(new java.awt.Color(255, 255, 255));
        btNumero1.setText("1");
        btNumero1.setToolTipText("Numero (35:1)");
        btNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero1ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero1);

        btNumero4.setBackground(new java.awt.Color(0, 0, 0));
        btNumero4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero4.setForeground(new java.awt.Color(255, 255, 255));
        btNumero4.setText("4");
        btNumero4.setToolTipText("Numero (35:1)");
        btNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero4ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero4);

        btNumero7.setBackground(new java.awt.Color(255, 0, 0));
        btNumero7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero7.setForeground(new java.awt.Color(255, 255, 255));
        btNumero7.setText("7");
        btNumero7.setToolTipText("Numero (35:1)");
        btNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero7ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero7);

        btNumero10.setBackground(new java.awt.Color(0, 0, 0));
        btNumero10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero10.setForeground(new java.awt.Color(255, 255, 255));
        btNumero10.setText("10");
        btNumero10.setToolTipText("Numero (35:1)");
        btNumero10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero10ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero10);

        btNumero13.setBackground(new java.awt.Color(0, 0, 0));
        btNumero13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero13.setForeground(new java.awt.Color(255, 255, 255));
        btNumero13.setText("13");
        btNumero13.setToolTipText("Numero (35:1)");
        btNumero13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero13ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero13);

        btNumero16.setBackground(new java.awt.Color(255, 0, 0));
        btNumero16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero16.setForeground(new java.awt.Color(255, 255, 255));
        btNumero16.setText("16");
        btNumero16.setToolTipText("Numero (35:1)");
        btNumero16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero16ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero16);

        btNumero19.setBackground(new java.awt.Color(255, 0, 0));
        btNumero19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero19.setForeground(new java.awt.Color(255, 255, 255));
        btNumero19.setText("19");
        btNumero19.setToolTipText("Numero (35:1)");
        btNumero19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero19ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero19);

        btNumero22.setBackground(new java.awt.Color(0, 0, 0));
        btNumero22.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero22.setForeground(new java.awt.Color(255, 255, 255));
        btNumero22.setText("22");
        btNumero22.setToolTipText("Numero (35:1)");
        btNumero22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero22ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero22);

        btNumero25.setBackground(new java.awt.Color(255, 0, 0));
        btNumero25.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero25.setForeground(new java.awt.Color(255, 255, 255));
        btNumero25.setText("25");
        btNumero25.setToolTipText("Numero (35:1)");
        btNumero25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero25ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero25);

        btNumero28.setBackground(new java.awt.Color(0, 0, 0));
        btNumero28.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero28.setForeground(new java.awt.Color(255, 255, 255));
        btNumero28.setText("28");
        btNumero28.setToolTipText("Numero (35:1)");
        btNumero28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero28ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero28);

        btNumero31.setBackground(new java.awt.Color(0, 0, 0));
        btNumero31.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero31.setForeground(new java.awt.Color(255, 255, 255));
        btNumero31.setText("31");
        btNumero31.setToolTipText("Numero (35:1)");
        btNumero31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero31ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero31);

        btNumero34.setBackground(new java.awt.Color(255, 0, 0));
        btNumero34.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero34.setForeground(new java.awt.Color(255, 255, 255));
        btNumero34.setText("34");
        btNumero34.setToolTipText("Numero (35:1)");
        btNumero34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero34ActionPerformed(evt);
            }
        });
        panelNumeros.add(btNumero34);

        panelColumnas.setBackground(new java.awt.Color(102, 255, 102));
        panelColumnas.setLayout(new java.awt.GridLayout(3, 1));

        btColumna3.setBackground(new java.awt.Color(153, 255, 153));
        btColumna3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btColumna3.setForeground(new java.awt.Color(0, 0, 0));
        btColumna3.setText("2 TO 1");
        btColumna3.setToolTipText("Columna (2:1)");
        btColumna3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColumna3ActionPerformed(evt);
            }
        });
        panelColumnas.add(btColumna3);

        btColumna2.setBackground(new java.awt.Color(153, 255, 153));
        btColumna2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btColumna2.setForeground(new java.awt.Color(0, 0, 0));
        btColumna2.setText("2 TO 1");
        btColumna2.setToolTipText("Columna (2:1)");
        btColumna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColumna2ActionPerformed(evt);
            }
        });
        panelColumnas.add(btColumna2);

        btColumna1.setBackground(new java.awt.Color(153, 255, 153));
        btColumna1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btColumna1.setForeground(new java.awt.Color(0, 0, 0));
        btColumna1.setText("2 TO 1");
        btColumna1.setToolTipText("Columna (2:1)");
        btColumna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColumna1ActionPerformed(evt);
            }
        });
        panelColumnas.add(btColumna1);

        btNumero0.setBackground(new java.awt.Color(0, 255, 0));
        btNumero0.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btNumero0.setForeground(new java.awt.Color(255, 255, 255));
        btNumero0.setText("0");
        btNumero0.setToolTipText("Numero (35:1)");
        btNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumero0ActionPerformed(evt);
            }
        });

        panelDocenas.setBackground(new java.awt.Color(102, 255, 102));
        panelDocenas.setLayout(new java.awt.GridLayout(1, 3));

        btDocena1.setBackground(new java.awt.Color(153, 255, 153));
        btDocena1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btDocena1.setForeground(new java.awt.Color(0, 0, 0));
        btDocena1.setText("1ra 12");
        btDocena1.setToolTipText("Columna (2:1)");
        btDocena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocena1ActionPerformed(evt);
            }
        });
        panelDocenas.add(btDocena1);

        btDocena2.setBackground(new java.awt.Color(153, 255, 153));
        btDocena2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btDocena2.setForeground(new java.awt.Color(0, 0, 0));
        btDocena2.setText("2da 12");
        btDocena2.setToolTipText("Columna (2:1)");
        btDocena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocena2ActionPerformed(evt);
            }
        });
        panelDocenas.add(btDocena2);

        btDocena3.setBackground(new java.awt.Color(153, 255, 153));
        btDocena3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btDocena3.setForeground(new java.awt.Color(0, 0, 0));
        btDocena3.setText("3ra 12");
        btDocena3.setToolTipText("Columna (2:1)");
        btDocena3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocena3ActionPerformed(evt);
            }
        });
        panelDocenas.add(btDocena3);

        panelColores.setBackground(new java.awt.Color(102, 255, 102));
        panelColores.setLayout(new java.awt.GridLayout(1, 6));

        btBajos.setBackground(new java.awt.Color(153, 255, 153));
        btBajos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btBajos.setForeground(new java.awt.Color(0, 0, 0));
        btBajos.setText("1 a 18");
        btBajos.setToolTipText("Alto/Bajo (1:1)");
        btBajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBajosActionPerformed(evt);
            }
        });
        panelColores.add(btBajos);

        btPar.setBackground(new java.awt.Color(153, 255, 153));
        btPar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btPar.setForeground(new java.awt.Color(0, 0, 0));
        btPar.setText("Par");
        btPar.setToolTipText("Par/Impar (1:1)");
        btPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParActionPerformed(evt);
            }
        });
        panelColores.add(btPar);

        btRojo.setBackground(new java.awt.Color(255, 0, 0));
        btRojo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btRojo.setForeground(new java.awt.Color(255, 255, 255));
        btRojo.setToolTipText("Color (1:1)");
        btRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRojoActionPerformed(evt);
            }
        });
        panelColores.add(btRojo);

        btNegro.setBackground(new java.awt.Color(0, 0, 0));
        btNegro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btNegro.setForeground(new java.awt.Color(255, 255, 255));
        btNegro.setToolTipText("Color (1:1)");
        btNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNegroActionPerformed(evt);
            }
        });
        panelColores.add(btNegro);

        btImpar.setBackground(new java.awt.Color(153, 255, 153));
        btImpar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btImpar.setForeground(new java.awt.Color(0, 0, 0));
        btImpar.setText("Impar");
        btImpar.setToolTipText("Par/Impar (1:1)");
        btImpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImparActionPerformed(evt);
            }
        });
        panelColores.add(btImpar);

        btAltos.setBackground(new java.awt.Color(153, 255, 153));
        btAltos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btAltos.setForeground(new java.awt.Color(0, 0, 0));
        btAltos.setText("19 a 36");
        btAltos.setToolTipText("Alto/Bajo (1:1)");
        btAltos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltosActionPerformed(evt);
            }
        });
        panelColores.add(btAltos);

        javax.swing.GroupLayout panelMesaHijoLayout = new javax.swing.GroupLayout(panelMesaHijo);
        panelMesaHijo.setLayout(panelMesaHijoLayout);
        panelMesaHijoLayout.setHorizontalGroup(
            panelMesaHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMesaHijoLayout.createSequentialGroup()
                .addComponent(btNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMesaHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                    .addComponent(panelDocenas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMesaHijoLayout.setVerticalGroup(
            panelMesaHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMesaHijoLayout.createSequentialGroup()
                .addGroup(panelMesaHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelColumnas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btNumero0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDocenas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelColores, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelMesaLayout = new javax.swing.GroupLayout(panelMesa);
        panelMesa.setLayout(panelMesaLayout);
        panelMesaLayout.setHorizontalGroup(
            panelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMesaHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMesaLayout.setVerticalGroup(
            panelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMesaHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btCerrar.setBackground(new java.awt.Color(153, 255, 153));
        btCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar.png"))); // NOI18N
        btCerrar.setToolTipText("Cerrar Ventana");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        labelTiempo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTiempo.setText("Tiempo de Apuestas: 15");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelFichas)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(panelMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelFichas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFichas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cerrarVentana();
    }//GEN-LAST:event_formWindowClosing

    private void tbFicha100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFicha100ActionPerformed
        // TODO add your handling code here:
        fichaSeleccionada = 100;
    }//GEN-LAST:event_tbFicha100ActionPerformed

    private void tbFichaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFichaBorrarActionPerformed
        // TODO add your handling code here:
        fichaSeleccionada = 0;
    }//GEN-LAST:event_tbFichaBorrarActionPerformed

    private void tbFicha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFicha1ActionPerformed
        // TODO add your handling code here:
        fichaSeleccionada = 1;
    }//GEN-LAST:event_tbFicha1ActionPerformed

    private void tbFicha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFicha2ActionPerformed
        // TODO add your handling code here:
        fichaSeleccionada = 2;
    }//GEN-LAST:event_tbFicha2ActionPerformed

    private void tbFicha5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFicha5ActionPerformed
        // TODO add your handling code here:
        fichaSeleccionada = 5;
    }//GEN-LAST:event_tbFicha5ActionPerformed

    private void tbFicha20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFicha20ActionPerformed
        // TODO add your handling code here:
        fichaSeleccionada = 20;
    }//GEN-LAST:event_tbFicha20ActionPerformed

    private void btRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRojoActionPerformed
        //Apostar a ROJO
        if (fichaSeleccionada == 0) {
            fichas += apuestaRojo;
            apuestaRojo = 0;
            btRojo.setText("");
            labelFichas.setText("Fichas: " + fichas);
        } else if (fichaSeleccionada > fichas) {
            JOptionPane.showMessageDialog(this, "No tiene suficientes fichas");
        } else {
            fichas -= fichaSeleccionada;
            apuestaRojo += fichaSeleccionada;
            btRojo.setText("" + apuestaRojo);
            labelFichas.setText("Fichas: " + fichas);
        }
    }//GEN-LAST:event_btRojoActionPerformed

    private void btNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNegroActionPerformed
        //Apostar a NEGRO
        if (fichaSeleccionada == 0) {
            fichas += apuestaNegro;
            apuestaNegro = 0;
            btNegro.setText("");
            labelFichas.setText("Fichas: " + fichas);
        } else if (fichaSeleccionada > fichas) {
            JOptionPane.showMessageDialog(this, "No tiene suficientes fichas");
        } else {
            fichas -= fichaSeleccionada;
            apuestaNegro += fichaSeleccionada;
            btNegro.setText("" + apuestaNegro);
            labelFichas.setText("Fichas: " + fichas);
        }
    }//GEN-LAST:event_btNegroActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
        cerrarVentana();
    }//GEN-LAST:event_btCerrarActionPerformed

    private void btNumero34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero34ActionPerformed
        // TODO add your handling code here:
        apostarNumero(34, btNumero34);
    }//GEN-LAST:event_btNumero34ActionPerformed

    private void btColumna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColumna1ActionPerformed
        // TODO add your handling code here:
        apostarColumna(0, btColumna1);
    }//GEN-LAST:event_btColumna1ActionPerformed

    private void btColumna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColumna2ActionPerformed
        // TODO add your handling code here:
        apostarColumna(1, btColumna2);
    }//GEN-LAST:event_btColumna2ActionPerformed

    private void btColumna3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColumna3ActionPerformed
        // TODO add your handling code here:
        apostarColumna(2, btColumna3);
    }//GEN-LAST:event_btColumna3ActionPerformed

    private void btNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero1ActionPerformed
        // TODO add your handling code here:
        apostarNumero(1, btNumero1);
    }//GEN-LAST:event_btNumero1ActionPerformed

    private void btNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero2ActionPerformed
        // TODO add your handling code here:
        apostarNumero(2, btNumero2);
    }//GEN-LAST:event_btNumero2ActionPerformed

    private void btNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero3ActionPerformed
        // TODO add your handling code here:
        apostarNumero(3, btNumero3);
    }//GEN-LAST:event_btNumero3ActionPerformed

    private void btNumero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero0ActionPerformed
        // TODO add your handling code here:
        apostarNumero(0, btNumero0);
    }//GEN-LAST:event_btNumero0ActionPerformed

    private void btNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero4ActionPerformed
        // TODO add your handling code here:
        apostarNumero(4, btNumero4);
    }//GEN-LAST:event_btNumero4ActionPerformed

    private void btNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero5ActionPerformed
        // TODO add your handling code here:
        apostarNumero(5, btNumero5);
    }//GEN-LAST:event_btNumero5ActionPerformed

    private void btNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero6ActionPerformed
        // TODO add your handling code here:
        apostarNumero(6, btNumero6);
    }//GEN-LAST:event_btNumero6ActionPerformed

    private void btNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero7ActionPerformed
        // TODO add your handling code here:
        apostarNumero(7, btNumero7);
    }//GEN-LAST:event_btNumero7ActionPerformed

    private void btNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero8ActionPerformed
        // TODO add your handling code here:
        apostarNumero(8, btNumero8);
    }//GEN-LAST:event_btNumero8ActionPerformed

    private void btNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero9ActionPerformed
        // TODO add your handling code here:
        apostarNumero(9, btNumero9);
    }//GEN-LAST:event_btNumero9ActionPerformed

    private void btNumero10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero10ActionPerformed
        // TODO add your handling code here:
        apostarNumero(10, btNumero10);
    }//GEN-LAST:event_btNumero10ActionPerformed

    private void btNumero11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero11ActionPerformed
        // TODO add your handling code here:
        apostarNumero(11, btNumero11);
    }//GEN-LAST:event_btNumero11ActionPerformed

    private void btNumero12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero12ActionPerformed
        // TODO add your handling code here:
        apostarNumero(12, btNumero12);
    }//GEN-LAST:event_btNumero12ActionPerformed

    private void btNumero13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero13ActionPerformed
        // TODO add your handling code here:
        apostarNumero(13, btNumero13);
    }//GEN-LAST:event_btNumero13ActionPerformed

    private void btNumero14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero14ActionPerformed
        // TODO add your handling code here:
        apostarNumero(14, btNumero14);
    }//GEN-LAST:event_btNumero14ActionPerformed

    private void btNumero15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero15ActionPerformed
        // TODO add your handling code here:
        apostarNumero(15, btNumero15);
    }//GEN-LAST:event_btNumero15ActionPerformed

    private void btNumero16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero16ActionPerformed
        // TODO add your handling code here:
        apostarNumero(16, btNumero16);
    }//GEN-LAST:event_btNumero16ActionPerformed

    private void btNumero17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero17ActionPerformed
        // TODO add your handling code here:
        apostarNumero(17, btNumero17);
    }//GEN-LAST:event_btNumero17ActionPerformed

    private void btNumero18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero18ActionPerformed
        // TODO add your handling code here:
        apostarNumero(18, btNumero18);
    }//GEN-LAST:event_btNumero18ActionPerformed

    private void btNumero19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero19ActionPerformed
        // TODO add your handling code here:
        apostarNumero(19, btNumero19);
    }//GEN-LAST:event_btNumero19ActionPerformed

    private void btNumero20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero20ActionPerformed
        // TODO add your handling code here:
        apostarNumero(20, btNumero20);
    }//GEN-LAST:event_btNumero20ActionPerformed

    private void btNumero21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero21ActionPerformed
        // TODO add your handling code here:
        apostarNumero(21, btNumero21);
    }//GEN-LAST:event_btNumero21ActionPerformed

    private void btNumero22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero22ActionPerformed
        // TODO add your handling code here:
        apostarNumero(22, btNumero22);
    }//GEN-LAST:event_btNumero22ActionPerformed

    private void btNumero23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero23ActionPerformed
        // TODO add your handling code here:
        apostarNumero(23, btNumero23);
    }//GEN-LAST:event_btNumero23ActionPerformed

    private void btNumero24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero24ActionPerformed
        // TODO add your handling code here:
        apostarNumero(24, btNumero24);
    }//GEN-LAST:event_btNumero24ActionPerformed

    private void btNumero25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero25ActionPerformed
        // TODO add your handling code here:
        apostarNumero(25, btNumero25);
    }//GEN-LAST:event_btNumero25ActionPerformed

    private void btNumero26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero26ActionPerformed
        // TODO add your handling code here:
        apostarNumero(26, btNumero26);
    }//GEN-LAST:event_btNumero26ActionPerformed

    private void btNumero27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero27ActionPerformed
        // TODO add your handling code here:
        apostarNumero(27, btNumero27);
    }//GEN-LAST:event_btNumero27ActionPerformed

    private void btNumero28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero28ActionPerformed
        // TODO add your handling code here:
        apostarNumero(28, btNumero28);
    }//GEN-LAST:event_btNumero28ActionPerformed

    private void btNumero29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero29ActionPerformed
        // TODO add your handling code here:
        apostarNumero(29, btNumero29);
    }//GEN-LAST:event_btNumero29ActionPerformed

    private void btNumero30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero30ActionPerformed
        // TODO add your handling code here:
        apostarNumero(30, btNumero30);
    }//GEN-LAST:event_btNumero30ActionPerformed

    private void btNumero31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero31ActionPerformed
        // TODO add your handling code here:
        apostarNumero(31, btNumero31);
    }//GEN-LAST:event_btNumero31ActionPerformed

    private void btNumero32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero32ActionPerformed
        // TODO add your handling code here:
        apostarNumero(32, btNumero32);
    }//GEN-LAST:event_btNumero32ActionPerformed

    private void btNumero33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero33ActionPerformed
        // TODO add your handling code here:
        apostarNumero(33, btNumero33);
    }//GEN-LAST:event_btNumero33ActionPerformed

    private void btNumero35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero35ActionPerformed
        // TODO add your handling code here:
        apostarNumero(35, btNumero35);
    }//GEN-LAST:event_btNumero35ActionPerformed

    private void btNumero36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumero36ActionPerformed
        // TODO add your handling code here:
        apostarNumero(36, btNumero36);
        for (JButton botone : botones) {
            System.out.println(botone.getText());
        }
    }//GEN-LAST:event_btNumero36ActionPerformed

    private void btDocena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocena1ActionPerformed
        // TODO add your handling code here:
        apostarDocenas(0, btDocena1, "1ra 12");
    }//GEN-LAST:event_btDocena1ActionPerformed

    private void btDocena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocena2ActionPerformed
        // TODO add your handling code here:
        apostarDocenas(1, btDocena2, "2da 12");
    }//GEN-LAST:event_btDocena2ActionPerformed

    private void btDocena3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocena3ActionPerformed
        // TODO add your handling code here:
        apostarDocenas(2, btDocena3, "3ra 12");
    }//GEN-LAST:event_btDocena3ActionPerformed

    private void btParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParActionPerformed
        // TODO add your handling code here:
        if (fichaSeleccionada == 0) {
            fichas += apuestaPar;
            apuestaPar = 0;
            btPar.setText("<html>"
                    + "  <h2 style=\"margin:0;\">Par</h2>"
                    + "  <h5 style=\"margin:0;\"></h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        } else if (fichaSeleccionada > fichas) {
            JOptionPane.showMessageDialog(this, "No tiene suficientes fichas");
        } else {
            fichas -= fichaSeleccionada;
            apuestaPar += fichaSeleccionada;
            btPar.setText("<html>"
                    + "  <h2 style=\"margin:0;\">Par</h2>"
                    + "  <h5 style=\"margin:0;\">" + apuestaPar + "</h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        }
    }//GEN-LAST:event_btParActionPerformed

    private void btImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImparActionPerformed
        // TODO add your handling code here:
        if (fichaSeleccionada == 0) {
            fichas += apuestaImpar;
            apuestaImpar = 0;
            btImpar.setText("<html>"
                    + "  <h2 style=\"margin:0;\">Impar</h2>"
                    + "  <h5 style=\"margin:0;\"></h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        } else if (fichaSeleccionada > fichas) {
            JOptionPane.showMessageDialog(this, "No tiene suficientes fichas");
        } else {
            fichas -= fichaSeleccionada;
            apuestaImpar += fichaSeleccionada;
            btImpar.setText("<html>"
                    + "  <h2 style=\"margin:0;\">Impar</h2>"
                    + "  <h5 style=\"margin:0;\">" + apuestaImpar + "</h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        }
    }//GEN-LAST:event_btImparActionPerformed

    private void btBajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBajosActionPerformed
        // TODO add your handling code here:
        apostarBajoAlto(0, btBajos, "1 a 18");
    }//GEN-LAST:event_btBajosActionPerformed

    private void btAltosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltosActionPerformed
        // TODO add your handling code here:
        apostarBajoAlto(1, btAltos, "19 a 36");
    }//GEN-LAST:event_btAltosActionPerformed
    
    private static int getRandomNumberInRange(int min, int max) {
        //Devuelve un numero al azar entre el rango que se le proporciona
        if (min >= max) {
            throw new IllegalArgumentException("max must be greater than min");
        }

        Random r = new Random();
        return r.nextInt((max - min) + 1) + min;
    }

    @Override
    public void run() {
        //Juega
        try {
            while (true) {
                //Tiempo de apuestas
                habilitar();
                for (int i = 15; i > 0; i--) {
                    labelTiempo.setText("Tiempo de Apuestas: " + i);
                    Thread.sleep(1000);
                }
                labelTiempo.setText("Tiempo de Apuestas: 0");
                deshabilitar();
                Thread.sleep(3000);

                //Numero aleatorio
                Resultado resultado = Mesa.getResultado(getRandomNumberInRange(0, 36));
                taLog.append("Sistema --> Ha salido el " + resultado.getNum() + "\n");
                //Paga y vuelve a girar
                pagar(resultado);
                Thread.sleep(3000);
            }
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un problema con el juego");
        }
    }

    public void habilitar() {
        //Habilita el tablero
        taLog.append("Mesa --> Hagan sus apuestas\n");

        for (Component component : panelNumeros.getComponents()) {
            component.setEnabled(true);
        }
        for (Component component : panelColores.getComponents()) {
            component.setEnabled(true);
        }
        for (Component component : panelColumnas.getComponents()) {
            component.setEnabled(true);
        }
        for (Component component : panelDocenas.getComponents()) {
            component.setEnabled(true);
        }
        btNumero0.setEnabled(true);
    }

    public void apostarNumero(int num, JButton boton) {
        //Apuesta a los numeros
        if (fichaSeleccionada == 0) {
            fichas += apuestaNumeros[num];
            apuestaNumeros[num] = 0;
            boton.setText("<html>"
                    + "  <h2 style=\"margin:0;\">" + num + "</h2>"
                    + "  <h5 style=\"margin:0;\"></h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        } else if (fichaSeleccionada > fichas) {
            JOptionPane.showMessageDialog(this, "No tiene suficientes fichas");
        } else {
            fichas -= fichaSeleccionada;
            apuestaNumeros[num] += fichaSeleccionada;
            boton.setText("<html>"
                    + "  <h2 style=\"margin:0;\">" + num + "</h2>"
                    + "  <h5 style=\"margin:0;\">" + apuestaNumeros[num] + "</h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        }
    }

    public void apostarColumna(int numCol, JButton boton) {
        //Apuesta a la columna seleccionada
        if (fichaSeleccionada == 0) {
            fichas += apuestaFilas[numCol];
            apuestaFilas[numCol] = 0;
            boton.setText("<html>"
                    + "  <h2 style=\"margin:0;\">2 TO 1</h2>"
                    + "  <h5 style=\"margin:0;\"></h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        } else if (fichaSeleccionada > fichas) {
            JOptionPane.showMessageDialog(this, "No tiene suficientes fichas");
        } else {
            fichas -= fichaSeleccionada;
            apuestaFilas[numCol] += fichaSeleccionada;
            boton.setText("<html>"
                    + "  <h2 style=\"margin:0;\">2 TO 1</h2>"
                    + "  <h5 style=\"margin:0;\">" + apuestaFilas[numCol] + "</h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        }
    }

    public void apostarDocenas(int numDocena, JButton boton, String label) {
        //Apuesta a la columna seleccionada
        if (fichaSeleccionada == 0) {
            fichas += apuestaDocenas[numDocena];
            apuestaDocenas[numDocena] = 0;
            boton.setText("<html>"
                    + "  <h2 style=\"margin:0;\">" + label + "</h2>"
                    + "  <h5 style=\"margin:0;\"></h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        } else if (fichaSeleccionada > fichas) {
            JOptionPane.showMessageDialog(this, "No tiene suficientes fichas");
        } else {
            fichas -= fichaSeleccionada;
            apuestaDocenas[numDocena] += fichaSeleccionada;
            boton.setText("<html>"
                    + "  <h2 style=\"margin:0;\">" + label + "</h2>"
                    + "  <h5 style=\"margin:0;\">" + apuestaDocenas[numDocena] + "</h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        }
    }
    
    public void apostarBajoAlto(int numBajoAlto, JButton boton, String label) {
        //Apuesta a la columna seleccionada
        if (fichaSeleccionada == 0) {
            fichas += apuestaBajo1Alto2[numBajoAlto];
            apuestaBajo1Alto2[numBajoAlto] = 0;
            boton.setText("<html>"
                    + "  <h2 style=\"margin:0;\">" + label + "</h2>"
                    + "  <h5 style=\"margin:0;\"></h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        } else if (fichaSeleccionada > fichas) {
            JOptionPane.showMessageDialog(this, "No tiene suficientes fichas");
        } else {
            fichas -= fichaSeleccionada;
            apuestaBajo1Alto2[numBajoAlto] += fichaSeleccionada;
            boton.setText("<html>"
                    + "  <h2 style=\"margin:0;\">" + label + "</h2>"
                    + "  <h5 style=\"margin:0;\">" + apuestaBajo1Alto2[numBajoAlto] + "</h5>"
                    + "</html>");
            labelFichas.setText("Fichas: " + fichas);
        }
    }

    private void setLabelsBotones() {
        //Limpia las labels de los botones de la mesa
        btNegro.setText("");
        btRojo.setText("");
        for (Component c : panelColumnas.getComponents()) {
            JButton boton = (JButton) c;
            boton.setText("2 TO 1");
        }

        int contador = 0;
        for (JButton b : botones) {
            b.setText(contador + "");
            contador++;
        }
        
        btDocena1.setText("1ra 12");
        btDocena2.setText("2da 12");
        btDocena3.setText("3ra 12");
        
        btBajos.setText("1 a 18");
        btAltos.setText("19 a 36");
        
        btPar.setText("Par");
        btImpar.setText("Impar");

    }

    public void deshabilitar() {
        //Deshabilita el tablero
        taLog.append("Mesa --> No más apuestas\n");

        for (Component component : panelNumeros.getComponents()) {
            component.setEnabled(false);
        }
        for (Component component : panelColores.getComponents()) {
            component.setEnabled(false);
        }
        for (Component component : panelColumnas.getComponents()) {
            component.setEnabled(false);
        }
        for (Component component : panelDocenas.getComponents()) {
            component.setEnabled(false);
        }
        btNumero0.setEnabled(false);
    }

    public void pagar(Resultado resultado) {
        int ganancias = 0;

        if (resultado.getNum() == 0) {
            //Se paga el 0
            ganancias += (apuestaNumeros[0] * 36);
        } else {
            //Numero (pleno)
            ganancias += (apuestaNumeros[resultado.getNum()] * 36);
            //Color
            if (resultado.getColor() == Color.RED) {
                ganancias += (apuestaRojo * 2);
            } else {
                ganancias += (apuestaNegro * 2);
            }
            //Par/Impar
            if (resultado.getPar() == 1) {
                //PAR, se pagan las ganancias
                ganancias += (apuestaPar * 2);
            } else {
                //IMPAR, se pagan las ganancias
                ganancias += (apuestaImpar * 2);
            }
            //Alto/Bajo
            ganancias += (apuestaBajo1Alto2[resultado.getBajo1Alto2() - 1] * 2);
            //Docenas
            ganancias += (apuestaDocenas[resultado.getDocena() - 1] * 3);
            //Filas
            ganancias += (apuestaFilas[resultado.getFila() - 1] * 3);

            //Pagar y actualizar variables y misc.
            taLog.append("Mesa --> Has ganado " + ganancias + " fichas!\n");
            fichas += ganancias;
            fichasPreApuesta = fichas;
            labelFichas.setText("Fichas: " + fichas);

            //Se limpia la mesa
            apuestaNegro = 0;
            apuestaRojo = 0;
            apuestaFilas = new int[3];
            apuestaDocenas = new int[3];
            apuestaBajo1Alto2 = new int[2];
            apuestaFilas = new int[3];
            apuestaNumeros = new int[37];
            apuestaPar = 0;
            apuestaImpar = 0;
            setLabelsBotones();
        }
    }

    public void cerrarVentana() {
        //Si hay apuestas en la mesa pregunta antes de cerrar
        if (fichas == fichasPreApuesta) {
            //Se cierra la ventana de jugar y vuelve al menu
            if (GestorUsuarios.getUsuarioActivo() != null) {
                GestorUsuarios.getUsuarioActivo().setFichasFinales(fichas);
            }
            m.setVisible(true);
            this.dispose();
        } else {
            //Hay apuestas en la mesa
            int eleccion = JOptionPane.showConfirmDialog(this, "Hay apuestas en la mesa, si sale estas fichas se perderán\n¿Desea salir?",
                    "Warning", JOptionPane.YES_NO_OPTION);
            switch (eleccion) {
                case 0:
                    if (GestorUsuarios.getUsuarioActivo() != null) {
                        GestorUsuarios.getUsuarioActivo().setFichasFinales(fichas);
                    }
                    m.setVisible(true);
                    this.dispose();
                    break;
                default:
                    break;
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltos;
    private javax.swing.JButton btBajos;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btColumna1;
    private javax.swing.JButton btColumna2;
    private javax.swing.JButton btColumna3;
    private javax.swing.JButton btDocena1;
    private javax.swing.JButton btDocena2;
    private javax.swing.JButton btDocena3;
    private javax.swing.JButton btImpar;
    private javax.swing.JButton btNegro;
    private javax.swing.JButton btNumero0;
    private javax.swing.JButton btNumero1;
    private javax.swing.JButton btNumero10;
    private javax.swing.JButton btNumero11;
    private javax.swing.JButton btNumero12;
    private javax.swing.JButton btNumero13;
    private javax.swing.JButton btNumero14;
    private javax.swing.JButton btNumero15;
    private javax.swing.JButton btNumero16;
    private javax.swing.JButton btNumero17;
    private javax.swing.JButton btNumero18;
    private javax.swing.JButton btNumero19;
    private javax.swing.JButton btNumero2;
    private javax.swing.JButton btNumero20;
    private javax.swing.JButton btNumero21;
    private javax.swing.JButton btNumero22;
    private javax.swing.JButton btNumero23;
    private javax.swing.JButton btNumero24;
    private javax.swing.JButton btNumero25;
    private javax.swing.JButton btNumero26;
    private javax.swing.JButton btNumero27;
    private javax.swing.JButton btNumero28;
    private javax.swing.JButton btNumero29;
    private javax.swing.JButton btNumero3;
    private javax.swing.JButton btNumero30;
    private javax.swing.JButton btNumero31;
    private javax.swing.JButton btNumero32;
    private javax.swing.JButton btNumero33;
    private javax.swing.JButton btNumero34;
    private javax.swing.JButton btNumero35;
    private javax.swing.JButton btNumero36;
    private javax.swing.JButton btNumero4;
    private javax.swing.JButton btNumero5;
    private javax.swing.JButton btNumero6;
    private javax.swing.JButton btNumero7;
    private javax.swing.JButton btNumero8;
    private javax.swing.JButton btNumero9;
    private javax.swing.JButton btPar;
    private javax.swing.JButton btRojo;
    private javax.swing.ButtonGroup grupoFichas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFichas;
    private javax.swing.JLabel labelTiempo;
    private javax.swing.JPanel panelColores;
    private javax.swing.JPanel panelColumnas;
    private javax.swing.JPanel panelDocenas;
    private javax.swing.JPanel panelFichas;
    private javax.swing.JPanel panelLog;
    private javax.swing.JPanel panelMesa;
    private javax.swing.JPanel panelMesaHijo;
    private javax.swing.JPanel panelNumeros;
    private javax.swing.JTextArea taLog;
    private javax.swing.JToggleButton tbFicha1;
    private javax.swing.JToggleButton tbFicha100;
    private javax.swing.JToggleButton tbFicha2;
    private javax.swing.JToggleButton tbFicha20;
    private javax.swing.JToggleButton tbFicha5;
    private javax.swing.JToggleButton tbFichaBorrar;
    // End of variables declaration//GEN-END:variables

}
