/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import BaseDatos.DataBase;
import Clases.ErrorException;
import Clases.GestorUsuarios;
import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Login l;
//
//    private Socket cliente;
//    private DataInputStream entrada;
//    private DataOutputStream salida;

    public Menu(Login l) {

        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Ruleta SF - Menú Principal");
        this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/login.png")).getImage());

        this.l = l;
//        this.cliente = cliente;

//        try {
//            //Inicializa los flujos
//            entrada = new DataInputStream(cliente.getInputStream()); //Canal de entrada
//            salida = new DataOutputStream(cliente.getOutputStream()); //canal de salida
//        } catch (IOException ex) {
//            JOptionPane.showMessageDialog(this, "Ha habido un problema conectandose con el servidor");
//        }
        
        if (GestorUsuarios.getUsuarioActivo() == null) {
            //Bloquea el boton de estadísticas
            btEstadisticas.setEnabled(false);
            btEstadisticas.setToolTipText("Debe haber iniciado sesion para tener acceso a sus estadísticas");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btJugar = new javax.swing.JButton();
        btEstadisticas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btCerrar = new javax.swing.JButton();
        btCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        btJugar.setText("JUGAR");
        btJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJugarActionPerformed(evt);
            }
        });

        btEstadisticas.setText("Estadísticas");
        btEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstadisticasActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo_RuletaSF.png"))); // NOI18N

        btCerrar.setText("CERRAR");
        btCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCerrarMouseExited(evt);
            }
        });
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        btCerrarSesion.setText("Cerrar Sesion");
        btCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCerrar)
                .addGap(83, 83, 83)
                .addComponent(btCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btJugar)
                .addGap(62, 62, 62)
                .addComponent(btEstadisticas)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCerrar)
                    .addComponent(btCerrarSesion))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Cerrar sesion y actualizar estadisticas de la sesion
        salir();
    }//GEN-LAST:event_formWindowClosing

    private void btJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJugarActionPerformed
        // TODO add your handling code here:
        Jugar j = new Jugar(this);
        j.setVisible(true);
        //Hilo para iniciar la ventana
        Thread hilo = new Thread(j);
        hilo.start();
        this.setVisible(false);
    }//GEN-LAST:event_btJugarActionPerformed

    private void btCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarMouseEntered
        // TODO add your handling code here:
        btCerrar.setBackground(Color.RED);
    }//GEN-LAST:event_btCerrarMouseEntered

    private void btCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarMouseExited
        // TODO add your handling code here:
        btCerrar.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_btCerrarMouseExited

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btCerrarActionPerformed

    private void btCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarSesionActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_btCerrarSesionActionPerformed

    private void btEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstadisticasActionPerformed
        // TODO add your handling code here:
        Estadisticas e = new Estadisticas(this);
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btEstadisticasActionPerformed

    public void cerrarSesion() {
        //Cierra sesion y vuelve a la pantalla de login
        if (GestorUsuarios.getUsuarioActivo() != null) {
            try {
                guardarEstadisticas();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Ha habido un problema guardando sus estadisticas\nSaliendo sin guardar.");
            } catch (ErrorException ex) {
                JOptionPane.showMessageDialog(this, "Ha habido un problema guardando sus estadisticas\nSaliendo sin guardar.");
            }
            GestorUsuarios.setUsuarioActivo(null);
        }
        l.setVisible(true);
        this.dispose();
    }

    public void salir() {
        //Cierra la aplicacion guardando las estadisticas

        if (GestorUsuarios.getUsuarioActivo() != null) {
            try {
                guardarEstadisticas();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Ha habido un problema guardando sus estadisticas\nSaliendo sin guardar.");
            } catch (ErrorException ex) {
                JOptionPane.showMessageDialog(this, "Ha habido un problema guardando sus estadisticas\nSaliendo sin guardar.");
            }
        }

        //Sale del programa
        System.exit(0);
    }

    public void guardarEstadisticas() throws SQLException, ErrorException {
        //Escribe las estadisticas en la BBDD
        PreparedStatement ps = null;

        ps = DataBase.getConexion().prepareStatement("INSERT INTO estadisticasusuario "
                + "(FECHAREALIZACION, FICHASINICIALES, FICHASFINALES, GANANCIAS, USUARIO_IDUSUARIO)  "
                + "values(SYSDATE, ?, ?, ?, ?)");
        ps.setInt(1, GestorUsuarios.getUsuarioActivo().getFichasIniciales());
        ps.setInt(2, GestorUsuarios.getUsuarioActivo().getFichasFinales());
        ps.setInt(3, GestorUsuarios.getUsuarioActivo().getFichasFinales() - GestorUsuarios.getUsuarioActivo().getFichasIniciales());
        ps.setInt(4, GestorUsuarios.getUsuarioActivo().getId());
        //Ejecuta
        DataBase.ejecutaUpdateSeguro(ps);
        
        //Escribe las fichas del usuario
            PreparedStatement ps2 = null;

            ps2 = DataBase.getConexion().prepareStatement("update usuario "
                    + "set FICHAS = ? "
                    + "where IDUSUARIO = ?");
            ps2.setInt(1, GestorUsuarios.getUsuarioActivo().getFichasFinales());
            ps2.setInt(2, GestorUsuarios.getUsuarioActivo().getId());
            
            //Ejecuta
            DataBase.ejecutaUpdateSeguro(ps2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btCerrarSesion;
    private javax.swing.JButton btEstadisticas;
    private javax.swing.JButton btJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
