/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import BaseDatos.DataBase;
import Clases.ErrorException;
import Clases.GestorUsuarios;
import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Login l;
//
//    private Socket cliente;
//    private DataInputStream entrada;
//    private DataOutputStream salida;

    public Menu(Login l) {

        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Ruleta SF - Menú Principal");
        this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/Logo.png")).getImage());
        this.setResizable(false);

        this.l = l;
//        this.cliente = cliente;

//        try {
//            //Inicializa los flujos
//            entrada = new DataInputStream(cliente.getInputStream()); //Canal de entrada
//            salida = new DataOutputStream(cliente.getOutputStream()); //canal de salida
//        } catch (IOException ex) {
//            JOptionPane.showMessageDialog(this, "Ha habido un problema conectandose con el servidor");
//        }
//        if (GestorUsuarios.getUsuarioActivo() == null) {
//            //Bloquea el boton de estadísticas
//            btEstadisticas.setEnabled(false);
//            btEstadisticas.setToolTipText("Debe haber iniciado sesion para tener acceso a sus estadísticas");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new PanelImagen.jPanelimagen();
        panelJugar = new PanelImagen.jPanelimagen();
        panelEstadisticas = new PanelImagen.jPanelimagen();
        btCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelFondo.setImagenFondo(new PanelImagen.ImagenFondo(new java.io.File("C:/Users/santi/OneDrive/SegundoDAM/Proyecto/MisArchivos/Ruleta SF/src/Recursos/fondo.jpg"),1.0f));

        panelJugar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelJugar.setImagenFondo(new PanelImagen.ImagenFondo(new java.io.File("C:/Users/santi/OneDrive/SegundoDAM/Proyecto/MisArchivos/Ruleta SF/src/Recursos/logoJugar.jpg"),1.0f));
        panelJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelJugarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelJugarLayout = new javax.swing.GroupLayout(panelJugar);
        panelJugar.setLayout(panelJugarLayout);
        panelJugarLayout.setHorizontalGroup(
            panelJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        panelJugarLayout.setVerticalGroup(
            panelJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        panelEstadisticas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEstadisticas.setImagenFondo(new PanelImagen.ImagenFondo(new java.io.File("C:/Users/santi/OneDrive/SegundoDAM/Proyecto/MisArchivos/Ruleta SF/src/Recursos/logoEstadisticas.jpg"),1.0f));
        panelEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEstadisticasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEstadisticasLayout = new javax.swing.GroupLayout(panelEstadisticas);
        panelEstadisticas.setLayout(panelEstadisticasLayout);
        panelEstadisticasLayout.setHorizontalGroup(
            panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        panelEstadisticasLayout.setVerticalGroup(
            panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        btCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar.png"))); // NOI18N
        btCerrar.setToolTipText("Cerrar Ventana");
        btCerrar.setContentAreaFilled(false);
        btCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCerrar.setFocusPainted(false);
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(panelJugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(panelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelJugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Cerrar sesion y actualizar estadisticas de la sesion
        salir();
    }//GEN-LAST:event_formWindowClosing

    private void panelEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEstadisticasMouseClicked
        // TODO add your handling code here:
            if (GestorUsuarios.getUsuarioActivo() != null) {
                Estadisticas e = new Estadisticas(this);
                e.setVisible(true);
                this.setVisible(false);
            }
    }//GEN-LAST:event_panelEstadisticasMouseClicked

    private void panelJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelJugarMouseClicked
            // TODO add your handling code here:
            Jugar j = new Jugar(this);
            j.setVisible(true);
            //Hilo para iniciar la ventana
            Thread hilo = new Thread(j);
            hilo.start();
            this.setVisible(false);
    }//GEN-LAST:event_panelJugarMouseClicked

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_btCerrarActionPerformed

    public void cerrarSesion() {
        //Cierra sesion y vuelve a la pantalla de login
        GestorUsuarios.setUsuarioActivo(null);
        l.setVisible(true);
        this.dispose();
    }

    public void salir() {
        //Sale del programa
        System.exit(0);
    }

    public void guardarEstadisticas() throws SQLException, ErrorException {
        //Escribe las estadisticas en la BBDD
        PreparedStatement ps = null;

        ps = DataBase.getConexion().prepareStatement("INSERT INTO estadisticasusuario "
                + "(FECHAREALIZACION, FICHASINICIALES, FICHASFINALES, GANANCIAS, USUARIO_IDUSUARIO)  "
                + "values(SYSDATE, ?, ?, ?, ?)");
        ps.setInt(1, GestorUsuarios.getUsuarioActivo().getFichasIniciales());
        ps.setInt(2, GestorUsuarios.getUsuarioActivo().getFichasFinales());
        ps.setInt(3, GestorUsuarios.getUsuarioActivo().getFichasFinales() - GestorUsuarios.getUsuarioActivo().getFichasIniciales());
        ps.setInt(4, GestorUsuarios.getUsuarioActivo().getId());
        //Ejecuta
        DataBase.ejecutaUpdateSeguro(ps);

        //Escribe las fichas del usuario
        PreparedStatement ps2 = null;

        ps2 = DataBase.getConexion().prepareStatement("update usuario "
                + "set FICHAS = ? "
                + "where IDUSUARIO = ?");
        ps2.setInt(1, GestorUsuarios.getUsuarioActivo().getFichasFinales());
        ps2.setInt(2, GestorUsuarios.getUsuarioActivo().getId());

        //Ejecuta
        DataBase.ejecutaUpdateSeguro(ps2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrar;
    private PanelImagen.jPanelimagen panelEstadisticas;
    private PanelImagen.jPanelimagen panelFondo;
    private PanelImagen.jPanelimagen panelJugar;
    // End of variables declaration//GEN-END:variables
}
