/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import BaseDatos.DataBase;
import java.awt.Color;
import javax.swing.ImageIcon;
import Clases.ErrorException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class NuevoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form NuevoUsuario
     */
    private Login l;

    public NuevoUsuario(Login l) {
        initComponents();

        this.l = l;

        this.setLocationRelativeTo(null);
        this.setTitle("Ruleta SF - Registrarse");
        this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/login.png")).getImage());
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelimagen1 = new PanelImagen.jPanelimagen();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jdFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        tfPassword1 = new javax.swing.JPasswordField();
        cbMostrarPassword = new javax.swing.JCheckBox();
        btCrear = new javax.swing.JButton();
        labelAtras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelimagen1.setImagenFondo(new PanelImagen.ImagenFondo(new java.io.File("C:/Users/santi/OneDrive/SegundoDAM/Proyecto/MisArchivos/Ruleta SF/src/Recursos/fondo.jpg"),1.0f));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Usuario");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("*Usuario: ");
        jLabel2.setToolTipText("OBLIGATORIO");

        tfUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfUsuario.setToolTipText("Nombre de usuario");
        tfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsuarioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo: ");

        tfCorreo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfCorreo.setToolTipText("Correo electrónico");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("*Fecha de Nacimiento: ");
        jLabel6.setToolTipText("OBLIGATORIO");

        jdFechaNacimiento.setBackground(new java.awt.Color(0, 51, 51));
        jdFechaNacimiento.setToolTipText("Fecha de nacimiento");
        jdFechaNacimiento.setDateFormatString("yyyy-MM-dd");
        jdFechaNacimiento.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*Contraseña: ");
        jLabel3.setToolTipText("OBLIGATORIO");

        tfPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfPassword.setToolTipText("Escriba su contraseña");
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*Conformar Contraseña: ");
        jLabel4.setToolTipText("OBLIGATORIO");

        tfPassword1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfPassword1.setToolTipText("Confirme su contraseña");
        tfPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassword1ActionPerformed(evt);
            }
        });

        cbMostrarPassword.setBackground(new java.awt.Color(0, 0, 0));
        cbMostrarPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbMostrarPassword.setForeground(new java.awt.Color(255, 255, 255));
        cbMostrarPassword.setText("Mostrar Contraseña");
        cbMostrarPassword.setOpaque(false);
        cbMostrarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMostrarPasswordActionPerformed(evt);
            }
        });

        btCrear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btCrear.setText("Darese de Alta");
        btCrear.setBorder(null);
        btCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });

        labelAtras.setForeground(new java.awt.Color(255, 255, 255));
        labelAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/arrowBack.png"))); // NOI18N
        labelAtras.setToolTipText("Volver");
        labelAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelimagen1Layout = new javax.swing.GroupLayout(jPanelimagen1);
        jPanelimagen1.setLayout(jPanelimagen1Layout);
        jPanelimagen1Layout.setHorizontalGroup(
            jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelimagen1Layout.createSequentialGroup()
                .addGap(0, 125, Short.MAX_VALUE)
                .addComponent(btCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(jPanelimagen1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelimagen1Layout.createSequentialGroup()
                        .addComponent(labelAtras)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1))
                    .addGroup(jPanelimagen1Layout.createSequentialGroup()
                        .addGroup(jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbMostrarPassword)
                                .addComponent(tfPassword1)
                                .addComponent(jdFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(tfCorreo)
                                .addComponent(tfUsuario))
                            .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelimagen1Layout.setVerticalGroup(
            jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelimagen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(labelAtras))
                .addGap(26, 26, 26)
                .addGroup(jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jdFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(jPanelimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(tfPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbMostrarPassword)
                .addGap(18, 18, 18)
                .addComponent(btCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelimagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelimagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsuarioActionPerformed
        // TODO add your handling code here:
        creaUsuario();
    }//GEN-LAST:event_tfUsuarioActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
        creaUsuario();
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void cbMostrarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMostrarPasswordActionPerformed
        // TODO add your handling code here:
        if (cbMostrarPassword.isSelected()) {
            tfPassword.setEchoChar((char) 0);
            tfPassword1.setEchoChar((char) 0);
        } else {
            tfPassword.setEchoChar('*');
            tfPassword1.setEchoChar('*');
        }
    }//GEN-LAST:event_cbMostrarPasswordActionPerformed

    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed
        // TODO add your handling code here:
        creaUsuario();
    }//GEN-LAST:event_btCrearActionPerformed

    private void tfPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassword1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void labelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAtrasMouseClicked
        // TODO add your handling code here:
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAtrasMouseClicked

    public static int calculateAge(LocalDate birthDate, LocalDate currentDate) {
        //Calcular edad de usuario
        if ((birthDate != null) && (currentDate != null)) {
            return Period.between(birthDate, currentDate).getYears();
        } else {
            return 0;
        }
    }

    public boolean existeNombre(String nombre) {
        //Comprueba si el nombre ya existe en la Base de Datos
        try {
            //Comprueba que el usuario esté en BBDD
            PreparedStatement ps = null;
            ResultSet rs = null;

            ps = DataBase.getConexion().prepareStatement("select NOMBRE from usuario "
                    + "where nombre = ?");
            ps.setString(1, nombre);

            rs = ps.executeQuery();

            return rs.next();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return false;
    }

    public void valida() throws ErrorException {
        //Valida los campos
        String password = "";
        String password2 = "";
        for (int i = 0; i < tfPassword.getPassword().length; i++) {
            password += tfPassword.getPassword()[i];
        }
        for (int i = 0; i < tfPassword1.getPassword().length; i++) {
            password2 += tfPassword1.getPassword()[i];
        }

        //Compara todos los campos
        Date hoy = new Date();
        if (tfUsuario.getText().length() == 0) {
            tfUsuario.requestFocus();
            throw new ErrorException("El nombre de usuario no puede estar vacio");
        } else if (existeNombre(tfUsuario.getText())) {
            tfUsuario.setText("");
            tfUsuario.requestFocus();
            throw new ErrorException("El nombre de usuario ya existe");
        } else if (tfCorreo.getText().length() != 0 && !tfCorreo.getText().matches(".+@.+\\..+")) {
            tfCorreo.setText("");
            tfCorreo.requestFocus();
            throw new ErrorException("El formato de correo no es correcto");
        } else if (jdFechaNacimiento.getDate() == null) {
            throw new ErrorException("La fecha de nacimiento no puede estar vacia");
        } else if (calculateAge(jdFechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), LocalDate.now()) < 18) {
            jdFechaNacimiento.setDate(null);
            throw new ErrorException("Debes ser mayor de 18 años para acceder a esta aplicación.");
        } else if (password.length() < 6) {
            tfPassword.setText("");
            tfPassword1.setText("");
            tfPassword.requestFocus();
            throw new ErrorException("La contraseña es demasiado debil.\nDebe contener al menos 6 caracteres");
        } else if (!password.equals(password2)) {
            tfPassword.setText("");
            tfPassword1.setText("");
            tfPassword.requestFocus();
            throw new ErrorException("Las contraseñas no coinciden");
        }
    }

    public void creaUsuario() {
        //Crea el usuario en bbdd validando los campos
        try {
            valida();
            //Una vez comprobado que esta correcto, se da de alta en BBDD
            String password = "";
            for (int i = 0; i < tfPassword.getPassword().length; i++) {
                password += tfPassword.getPassword()[i];
            }
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
            PreparedStatement ps = null;

            ps = DataBase.getConexion().prepareStatement("INSERT INTO usuario "
                    + "(NOMBRE, FECHANACIMIENTO, CORREO, FECHACREACION, FICHAS, CONTRASENA)  "
                    + "values(?, ?, ?, SYSDATE, 1000, ?)");
            ps.setString(1, tfUsuario.getText());
            ps.setString(2, sdf.format(jdFechaNacimiento.getDate()));
            if (tfCorreo.getText().length() == 0) {
                ps.setString(3, null);
            } else {
                ps.setString(3, tfCorreo.getText());
            }
            ps.setString(4, password);

            //Ejecuta
            DataBase.ejecutaUpdateSeguro(ps);

            //Mensaje de éxito
            JOptionPane.showMessageDialog(this, "Se ha creado el usuario con éxito!", "Informacion", JOptionPane.INFORMATION_MESSAGE);

            //Cierra la pestaña y carga los parametros en el login
            l.setParametros(tfUsuario.getText(), password);
            l.setVisible(true);
            this.dispose();
        } catch (ErrorException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Ha habido un problema guardando el usuario en Base de Datos");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrear;
    private javax.swing.JCheckBox cbMostrarPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private PanelImagen.jPanelimagen jPanelimagen1;
    private com.toedter.calendar.JDateChooser jdFechaNacimiento;
    private javax.swing.JLabel labelAtras;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JPasswordField tfPassword1;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
